[lb]
lb-1 ansible_host=192.168.57.101 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/lb-1/libvirt/private_key

[web]
web-1 ansible_host=192.168.57.121 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-1/libvirt/private_key
web-2 ansible_host=192.168.57.122 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-2/libvirt/private_key
web-3 ansible_host=192.168.57.123 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-3/libvirt/private_key
web-4 ansible_host=192.168.57.124 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-4/libvirt/private_key
web-5 ansible_host=192.168.57.125 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-5/libvirt/private_key
web-6 ansible_host=192.168.57.126 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-6/libvirt/private_key
web-7 ansible_host=192.168.57.127 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-7/libvirt/private_key
web-8 ansible_host=192.168.57.128 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-8/libvirt/private_key
web-9 ansible_host=192.168.57.129 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/web-9/libvirt/private_key

[dns]
dns-1 ansible_host=192.168.57.111 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-1/libvirt/private_key
dns-2 ansible_host=192.168.57.112 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-2/libvirt/private_key
dns-3 ansible_host=192.168.57.113 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-3/libvirt/private_key
dns-4 ansible_host=192.168.57.114 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-4/libvirt/private_key
dns-5 ansible_host=192.168.57.115 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-5/libvirt/private_key
dns-6 ansible_host=192.168.57.116 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-6/libvirt/private_key
dns-7 ansible_host=192.168.57.117 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-7/libvirt/private_key
dns-8 ansible_host=192.168.57.118 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-8/libvirt/private_key
dns-9 ansible_host=192.168.57.119 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/dns-9/libvirt/private_key